### ISSUE TITLE
update to latest bidict

### ISSUE THREAD

**Issue by jab** [venmo/btnamespace#6]
Hey @simon-weber, I noticed this project uses my bidict library (nice!), but it's [pinned to a pretty old version](https://github.com/venmo/btnamespace/commit/4db475af212c1e01ef33b200d21c0b3741102c57). Just wanted to let you know there have been some significant improvements since the version you're using. A summary of notable changes can be found here:

https://bidict.readthedocs.io/changelog.html

If you're interested in updating and have any questions, I'd be happy to try to help. Otherwise, please close this and feel free to ignore. :)

**Comment by simon-weber** [comment]
I think I pinned it after one of the breaking changes, haha. I'll leave this open, but if everything is working I'm not sure there's much incentive for us to upgrade 😁

**Comment by jab** [comment]
The version you're pinned to has a couple WAT-level bugs (in `pop()` and `setdefault()`): 🙊  😢 
```python
>>> from bidict import bidict
>>> b = bidict({1: 2})
>>> b.pop(3, 4)  # should return 4, not raise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python2.7/site-packages/bidict.py", line 620, in pop
    del self._bwd[val]
KeyError: 4
>>> b = bidict({1: 2})
>>> b.setdefault(3, 2)
2
>>> b
bidict({1: 2, 3: 2})
>>> b.inv
bidict({2: 3})
```
These were fixed a few versions back in [0.10.0](https://bidict.readthedocs.io/en/master/changelog.html#id5). That version is also significant because starting from that version, if you try to set an item that duplicates the value of an existing item, an exception is raised to protect you from accidentally overwriting the existing item, rather than silently replacing it potentially without you realizing. With the version you have now, this is what happens:
```python
>>> b = bidict({1: 2})
>>> b[3] = 2
>>> b  # you might not expect this:
bidict({3: 2})
>>> b = bidict({1: 2, 3: 4})
>>> b[1] = 4
>>> b  # or this:
bidict({1: 4})
```
The `ValueDuplicationError` that is now thrown has saved users from unwittingly shooting themselves in the foot. A recent testimonial from someone in https://gitter.im/jab/bidict: "@jab: The new exception saved me from a serious bug that I probably wouldn't have seen otherwise. Thanks!"

In case any of those offer enough incentive!

**Comment by jab** [comment]
(Check out http://bidict.readthedocs.io/en/v0.12.0/basic-usage.html#uniqueness-of-values for more docs on handling value duplication.)

**Comment by simon-weber** [comment]
Haha, ok, I'll look into upgrading. Thanks!

**Comment by jab** [comment]
Sure thing, let me know if you have any questions!
